export const types = [
  "Planet",
  "Cluster",
  "unknown",
  "Microverse",
  "Fantasy town",
  "Space station",
  "Dream",
  "Dimension",
  "Menagerie",
  "Game",
  "Customs",
  "Daycare",
  "Dwarf planet (Celestial Dwarf)",
  "Teenyverse",
  "Box",
  "Spacecraft",
  "Arcade",
  "Spa",
].sort((a, b) => a < b ? -1 : 1);
export const dimensions = [
    "Dimension C-137", 
    "unknown",
    "Post-Apocalyptic Dimension",
    "Replacement Dimension",
    "Cronenberg Dimension",
    "Fantasy Dimension",
    "Dimension 5-126",
    "Testicle Monster Dimension",
    "Cromulon Dimension",
    "Dimension C-500A",
    "Dimension K-83",
    "Dimension J19ζ7",
    "Eric Stoltz Mask Dimension",
    "Evil Rick's Target Dimension",
    "Giant Telepathic Spiders Dimension",
    "Dimension D-99",
    "Dimension D716",
    "Dimension D716-B",
    "Dimension D716-C",
    "Dimension J-22",
    "Dimension C-35",
    "Pizza Dimension",
    "Phone Dimension",
    "Chair Dimension",
    "Fascist Shrimp Dimension"
].sort((a, b) => a < b ? -1 : 1);
